### ISSUE TITLE
关于log接口对log进行查看

### ISSUE THREAD

**Issue by GamerNoTitle** [bili-vd-bak/biliroaming-ts-server-vercel#10]
在用这个项目的时候（部署在vercel），发现有需要查log的需求，在api文件夹找到了log的api接口为`/api/admin/log?s=secret`，但是实际上这样去进行访问后，网页只返回了一个`{}`，并没有任何实质性的内容。所以就是想问问这个api的正确用法是怎么样的，目标是看到运行的log，谢谢

**Comment by xrz-cloud** [comment]
此接口主要是用于本地部署时查看log，Vercel由于Serverless会重置环境，故建议直接在Vercel-Project-Log内查看
