### ISSUE TITLE
获取服务器状态失败

### ISSUE THREAD

**Issue by JasonZH6600** [bili-vd-bak/biliroaming-ts-server-vercel#13]
感谢大佬![Screenshot_2023-10-19-10-55-52-868_com.microsoft.emmx.jpg](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/assets/100362620/4042f09e-c221-426e-a5f0-0ccd9a1db372)

**Comment by xrz-cloud** [comment]
已解决

**Comment by JasonZH6600** [comment]
感谢大佬
