### ISSUE TITLE
初始化数据库显示密码错误

### ISSUE THREAD

**Issue by ACGAPI** [bili-vd-bak/biliroaming-ts-server-vercel#15]
按步骤在Vercel项目Storage里连接数据，并将 db_bitio_enabled 设为1后，初始化数据库显示秘钥错误，秘钥填的星号里的
![image](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/assets/87590718/f968e2c2-b77a-48b3-9860-565c6486a5b1)
![image](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/assets/87590718/03bd9811-23a7-4b69-bea1-e58d8028cb68)

**Comment by xrz-cloud** [comment]
请阅读本仓库wiki,该secret为 `本地数据库查询密钥`即`local_cache_secret`.  

> 请求 `/admin/*` api时,该secret key为配置`_config.ts`/对应环境变量 [此处](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/blob/master/src/_config.ts#L204)
