### ISSUE TITLE
反代后在哔哩uwp等桌面端无法使用

### ISSUE THREAD

**Issue by tanji2005** [bili-vd-bak/biliroaming-ts-server-vercel#17]
通过排查日志直接访问类似
https://xxxxx.com/pgc/player/web/playurl?appkey=27eb53fc9058f8c3&cid=1053991467&ep_id=713747&qn=80&type=&otype=json&module=bangumi&season_type=1&access_key={hasValue}&mid=499099283&fourk=1&fnver=0&fnval=4048&sign={hasValue}&area=hk
得到结果如下
{
  "code": -412,
  "message": "()(E=1)"
}
还有想问一下access key无法获取，将获取到的cookie填入访问，输出结果为空。

**Comment by tanji2005** [comment]
测试了在手机端的哔哩漫游正常

**Comment by ywmoyue** [comment]
@tanji2005  这个代理服务报错的E=1意思是禁止Web请求
需要修改配置允许web请求：https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6#%E9%99%90%E5%88%B6api%E8%B0%83%E7%94%A8

**Comment by xrz-cloud** [comment]
cookie获取功能可能有点问题，能否获取有点玄学，也许是字符串格式化的问题。
目前仅保证在移动端漫游正常运行，油猴脚本应该也可以。
不过最近B站在对API做限制，可能也会有影响。
