### ISSUE TITLE
web版搜索api限制

### ISSUE THREAD

**Issue by xrz-cloud** [bili-vd-bak/biliroaming-ts-server-vercel#3]
使用web搜索api会返回-412  
原因：可能是未接受cookies并未转发至biliAPI  
见[搜索API](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/search/search_request.md)  

解决方法：  
转发客户端cookie  
或 服务端识别`searchType`并用手机端API请求，并合成为web格式response

**Comment by gaosen1** [comment]
> 

（疑惑）手机端API是什么？
我在开发中也遇到了这个问题，使用web搜索的api，vercel的functions日志那里报错，返回-412，但是我看抓包分析的请求头、响应头里也有我配置的cookies.

**Comment by gaosen1** [comment]
真折磨..解决了吗

**Comment by gaosen1** [comment]
我发现是我cookie配错地方了..，之前是写在``vercel.json``中，改为写在``api/search.ts``中后，返回200.
但是请求到的数据是这样的乱码：
{"status":"ojbkkkk","data":"\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003�}ks\u0014W��_��~��[m���\u001b7b�=ݞn��/�o�\u001dO\u0010�\u0004\r ђ��ӷ#$��$\u0010\b\u0010O\t\u0004��\u0001\t\f\u0006�\u0017\u0011�y~�]�U���\tw�̬��T�\u0014�-˥�<�'�9k��������!?��A*����\u0011g\u0017|�'����ѽ�;h��wF��\u001d�\u001f\t\u0006|
....（后面还有很多）
也不知道是什么编码格式，unicode？尝试了一些在线解码平台，都没有解码出正常的。
使用postman测试，部分响应头如下：
``Content-Encoding: br``
``Content-Type:application/json: harset=utf-8``
``Transfer-Encoding: chunked``
我认为解决该问题的关键是``Content-Encoding``应该是``gzip``，因为在web端b站请求搜索接口的响应头中，``Content-Encoding``的值就是``gzip``：
![Snipaste_2022-11-25_14-07-05](https://user-images.githubusercontent.com/75928758/203912417-b26ce26c-3f09-46f2-a9be-a057f5a83c57.png)

但我在``vercel.json``中配置了``headers.Content-Encoding``，它似乎没有起作用.
部分``vercel.json``:
```json
{
  "rewrites": [
    {
      "source": "/search",
      "destination": "/api/search"
    }
  ],
"headers": [
    {
      "source": "/search",
      "headers": [
        {
          "key": "access-control-allow-headers",
          "value": "Cache-Control,Content-Encoding,No-Cache"
        },
        {
          "key": "access-control-allow-headers",
          "value": "Content-Type"
        },
        {
          "key": "Transfer-Encoding",
          "value": "chunked"
        },
        {
          "key": "content-encoding",
          "value": "gzip"
        },
        {
          "key": "content-type",
          "value": "application/json; charset=utf-8"
        },
      ]
    }
  ]
}
```

**Comment by xrz-cloud** [comment]
> B站于2022年8月24日更新了搜索api，增加了一大堆Cookies的校验，如果Cookies不足会返回-412搜索被拦截。如果没有cookies的话，请在搜索之前先GET一遍 https://bilibili.com/ 以获取cookies
详情见https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/search/search_request.md

提前获取游客cookie即可
```typescript
/**
 * 获取Bilibili网页版游客Cookies
 */
export const getCookies = async () => {
  return await fetch("https://www.bilibili.com/").then((res) => {
    //代码来源
    /*本文作者： cylee'贝尔塔猫
      本文链接： https://www.cnblogs.com/CyLee/p/16170228.html
      关于博主： 评论和私信会在第一时间回复。或者直接私信我。
      版权声明： 本博客所有文章除特别声明外，均采用 BY-NC-SA 许可协议。转载请注明出处！*/

    // 获取 cookie
    const cookie = res.headers.get("set-cookie") || "";
    // 清理一下 cookie 的格式，移除过期时间，只保留基础的键值对才能正常使用
    const real_cookie = cookie
      .replace(/expires=(.+?);\s/gi, "")
      .replace(/path=\/(,?)(\s?)/gi, "")
      .trim();
    return real_cookie;
  });
};
```

调用见https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/blob/master/api/x/web-interface/search/type.ts
